"use client";

import * as React from "react";
import Link from "next/link";
import {
  FileText,
  Download,
  Share2,
  Eye,
  CheckCircle,
  XCircle,
  AlertTriangle,
  MoreHorizontal,
  Copy,
  Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

const mockReports = [
  {
    id: "1",
    project: "Loan Approval Model v2.3",
    type: "compliance",
    createdAt: "2 hours ago",
    score: 0.78,
    violations: 2,
  },
  {
    id: "2",
    project: "Credit Risk Assessment",
    type: "summary",
    createdAt: "1 day ago",
    score: 0.92,
    violations: 0,
  },
  {
    id: "3",
    project: "Employee Screening AI",
    type: "detailed",
    createdAt: "3 days ago",
    score: 0.65,
    violations: 3,
  },
  {
    id: "4",
    project: "Housing Approval Model",
    type: "compliance",
    createdAt: "1 week ago",
    score: 0.84,
    violations: 1,
  },
];

import { useRouter } from "next/navigation";

export default function ReportsPage() {
  const router = useRouter();
  const handleExportAll = () => {
    let allReports = "# FairLens Audit Reports\n\n";
    mockReports.forEach((report) => {
      allReports += `## ${report.project}\n`;
      allReports += `- Type: ${report.type}\n`;
      allReports += `- Created: ${report.createdAt}\n`;
      allReports += `- Fairness Score: ${Math.round(report.score * 100)}%\n`;
      allReports += `- Violations: ${report.violations}\n\n`;
    });
    
    const blob = new Blob([allReports], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'all-reports.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleView = (report: typeof mockReports[0]) => {
    router.push(`/demo/projects/${report.id}`);
  };

  const handleDownload = (report: typeof mockReports[0]) => {
    const content = `# ${report.project}\n\n## Report Details\n- Type: ${report.type}\n- Created: ${report.createdAt}\n- Fairness Score: ${Math.round(report.score * 100)}%\n- Violations: ${report.violations}\n\n---\nGenerated by FairLens`;
    
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.project.toLowerCase().replace(/\s+/g, '-')}-report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = (report: typeof mockReports[0]) => {
    navigator.clipboard.writeText(`Check out my fairness audit report for ${report.project}! Fairness Score: ${Math.round(report.score * 100)}%`);
    alert("Link copied to clipboard!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Audit Reports</h1>
          <p className="text-muted-foreground">View and download your fairness audit reports</p>
        </div>
        <Button variant="outline" className="gap-2" onClick={handleExportAll}>
          <Download className="h-4 w-4" />
          Export All
        </Button>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {mockReports.map((report) => (
          <div
            key={report.id}
            className="rounded-xl border border-border bg-card p-5 hover:border-primary/50 transition-colors"
          >
            <div className="mb-4 flex items-start justify-between">
              <div className="flex items-center gap-3">
                <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
                  <FileText className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <p className="font-medium">{report.project}</p>
                  <p className="text-sm text-muted-foreground">{report.createdAt}</p>
                </div>
              </div>
              <Button variant="ghost" size="icon">
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </div>

            <div className="mb-4 flex items-center gap-2">
              <Badge variant="outline" className="capitalize">{report.type}</Badge>
              <Badge variant={report.score >= 0.8 ? "default" : "destructive"}>
                Score: {Math.round(report.score * 100)}%
              </Badge>
              {report.violations > 0 && (
                <Badge variant="destructive">
                  <AlertTriangle className="mr-1 h-3 w-3" />
                  {report.violations} Issues
                </Badge>
              )}
            </div>

            <div className="flex gap-2">
              <Button variant="outline" size="sm" className="flex-1 gap-2" onClick={() => handleView(report)}>
                <Eye className="h-4 w-4" />
                View
              </Button>
              <Button variant="outline" size="sm" className="flex-1 gap-2" onClick={() => handleDownload(report)}>
                <Download className="h-4 w-4" />
                PDF
              </Button>
              <Button variant="outline" size="sm" onClick={() => handleShare(report)}>
                <Share2 className="h-4 w-4" />
              </Button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}